### ISSUE TITLE
Module could not be loaded, unmapped packet

### ISSUE THREAD

**Issue by MeowyMeow** [Owyn/infinity-journal#2]
Hi, I got this error trying to load the module on caali's tera toolbox.
[10:16:08.401] Error: [dispatch] hook: unmapped packet "S_PCBANGINVENTORY_DATALIST"
    at Dispatch.createHook (C:\Users\weapo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\weapo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:298:27)
    at Module.hook (C:\Users\weapo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at new InfinityJournal (C:\Users\weapo\AppData\Local\Programs\TeraToolbox\mods\infinity-journal-master\index.js:82:11)
    at ModuleManager.load (C:\Users\weapo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:156:35)
    at C:\Users\weapo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\weapo\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:119:31)
    at Socket.<anonymous> (C:\Users\weapo\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:54:47)
    at Socket.emit (events.js:199:15)

**Comment by Owyn** [comment]
should work now
